name: tarefas
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=2.19.6 <3.0.0'

dependencies:
  http: ^0.13.3
  uuid: ^3.0.7
  logger: ^1.4.0
  http_interceptor: ^1.0.2
  shared_preferences: ^2.2.0
  flutter:
    sdk: flutter
  


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  

flutter:
  uses-material-design: true

  assets:
    - assets/images/