// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAeig3DDb8jw1-bc7VzglDTf0aE40iIsWQ',
    appId: '1:476755732089:web:58e53e1c681b723dd556a8',
    messagingSenderId: '476755732089',
    projectId: 'primeiro-app-tarefas',
    authDomain: 'primeiro-app-tarefas.firebaseapp.com',
    storageBucket: 'primeiro-app-tarefas.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCpGCMh44hopEg9NuYy3VJyfwYhOiXOcIY',
    appId: '1:476755732089:android:4b75e22b6ceab7c2d556a8',
    messagingSenderId: '476755732089',
    projectId: 'primeiro-app-tarefas',
    storageBucket: 'primeiro-app-tarefas.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCaeU5Qa4L2VVHj96I9Wkxt2_-frXMsCZ0',
    appId: '1:476755732089:ios:eef03eeb80dc3751d556a8',
    messagingSenderId: '476755732089',
    projectId: 'primeiro-app-tarefas',
    storageBucket: 'primeiro-app-tarefas.appspot.com',
    iosClientId: '476755732089-7tpr40tr1fhq965uo66i7c83ovqpocqi.apps.googleusercontent.com',
    iosBundleId: 'com.example.tarefas',
  );
}
